name: Autotest
on: [push, pull_request]

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest
    container:
      image: xakki/phpwall-php:8.1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Vendor
        run: composer install

      - name: Run PHPSTAN
        run: composer phpstan

      - name: Run CodeStyle check
        run: composer cs-check

      - name: PhpUnit
        run: composer phpunit
